### ISSUE TITLE
Only block ads in snapchat

### ISSUE THREAD

**Issue by ztjuh** [nickoppen/pihole-blocklists#1]
Hey Nick,

Thanks for the list! May god bless you 💫🌟✨

Is there a list which only blocks the ads in snapchat and not snapchat entirely? 

Heartly regards,
Alex

**Comment by nickoppen** [comment]
Thank you Alex,

Regarding ad lists on snapchat - I have not been focussing on ads specifically because there are a number of other lists that do that. Having said that, they are mainly general lists and not those who advertise on one platform specifically.

My kids use snapchat so when I get a chance I'll have a look at the dns activity and see if the advertisers can be isolated out. It may be possible to generate a list from the pihole trace.

Cheers,

nick

**Comment by ztjuh** [comment]
Okay, thank you! I will try to find a other list!

Op vr 24 feb. 2023 02:12 schreef Nick Oppen ***@***.***>:

**Comment by ztjuh** [comment]
Because of the AI it is using to manipulate the pictures, I removed Snapchat from my phone and deleted/removed my account.  I don't know if Snapchat saves your data but just to be sure.

Problem solved indeed! 😂

**Comment by nickoppen** [comment]
https://github.com/gieljnssns/Social-media-Blocklists/blob/master/pihole-instagram.txt might be what you are after.

**Comment by ztjuh** [comment]
I pray I would like to spread the Gospel of Jesus Christ,
Amen 🏔️⛰️🌋🏝️🌆🛬🇦🇨🇦🇽🇧🇶🇧🇻🇨🇨🇨🇭🇨🇰🇨🇵🇨🇽🇫🇮🇫🇰🇫🇴🇬🇧🇬🇱🇬🇸🇭🇲🇮🇨🇮🇪🇮🇸🇰🇾🇲🇭🇲🇵🇳🇫🇳🇱🇳🇿🇵🇱🇵🇳🇸🇧🇹🇨🇹🇭🇺🇲🇻🇬🇻🇮🏴󠁧󠁢󠁥󠁮󠁧󠁿🏴󠁧󠁢󠁳󠁣󠁴󠁿💂🏻
